### ISSUE TITLE
建议 GPU 环境搭建文档补充说明下 CUDA 版本

### ISSUE THREAD

**Issue by Longxr** [lazydog28/mc_auto_boss#76]
我直接装了个 12.5.0 的 CUDA，走到后面各种报错，换成老版本就好了

## CUDA 下载安装

[CUDA 历史版本下载](https://developer.nvidia.com/cuda-toolkit-archive)
[cuDNN 历史版本下载](https://developer.nvidia.com/rdp/cudnn-archive)

官网最新的 CUDA 已经到了 12.5.0 (May 2024)，不建议直接用最新版。下面相关的 python 库对于 CUDA 的支持是有版本要求的，如 [paddlepaddle-gpu 对应 CUDA 版本](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/windows-pip.html#shouxianqingninxuanzenindebanben)，下方安装命令中对应的是 CUDA 11.7，cuDNN v8.4.1。

**Comment by lazydog28** [comment]
感谢你的贡献，已经更新wiki

**Comment by yeming1999** [comment]
...我说怎么回事，上周末试了半天，一会装11.8，一会装12.5，每次都报错

**Comment by yeming1999** [comment]
我遇到的问题：
1、我的用户名称是中文，但若C盘模型文件存在中文，则会报错找不到模型，此时需要放在另一个不含中文的目录，并修改background/ocr.py文件，指明模型存放的地址（我是在C盘新增的paddleocr_models文件夹，将C:\Users\用户\.paddleocr\whl\det\ch的模型放了过来）
完整的ocr.py内容：
import os
import sys
import time  # 确保导入 time 模块

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
import init
from mouse_reset import mouse_reset
from multiprocessing import current_process
import numpy as np
from schema import OcrResult, Position
from config import config
from paddleocr import PaddleOCR
import logging

# 检查模型路径
det_model_dir = 'C:/paddleocr_models/ch_PP-OCRv4_det_infer'
rec_model_dir = 'C:/paddleocr_models/ch_PP-OCRv4_rec_infer'
print(f"Det Model directory exists: {os.path.exists(det_model_dir)}")
print(f"Det Model file exists: {os.path.exists(os.path.join(det_model_dir, 'inference.pdmodel'))}")
print(f"Rec Model directory exists: {os.path.exists(rec_model_dir)}")
print(f"Rec Model file exists: {os.path.exists(os.path.join(rec_model_dir, 'inference.pdmodel'))}")

ocrIns: PaddleOCR = None

if current_process().name == "task":
    logging.disable(logging.WARNING)  # 关闭WARNING日志的打印
    ocrIns = PaddleOCR(det_model_dir=det_model_dir, rec_model_dir=rec_model_dir, use_angle_cls=False, use_gpu=True, lang="ch", show_log=False)

last_time = time.time()

def ocr(img: np.ndarray) -> list[OcrResult]:
    global last_time
    if config.OcrInterval > 0 and time.time() - last_time < config.OcrInterval:  # 限制OCR调用频率
        if wait_time := config.OcrInterval - (time.time() - last_time) > 0:
            time.sleep(wait_time)
    last_time = time.time()
    results = ocrIns.ocr(img)[0]
    if not results:
        return []
    res = []
    for result in results:
        text = result[1][0]
        position = result[0]
        x1, y1, x2, y2 = position[0][0], position[0][1], position[2][0], position[2][1]
        position = Position(x1=x1, y1=y1, x2=x2, y2=y2)
        confidence = result[1][1]
        res.append(OcrResult(text=text, position=position, confidence=confidence))
    return res

**Comment by yeming1999** [comment]
2、报错依赖冲突 ”ERROR: Cannot install onnxruntime-gpu==1.17.0 and paddlepaddle-gpu==2.6.1 because these package versions have conflicting dependencies.“、” ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies“
可尝试
1、升级pip：python -m pip install --upgrade pip
2、安装特定版本的protobuf：pip uninstall protobuf
pip install protobuf==3.20.2
3、安装依赖：pip install -r requirements.txt
目前这是我遇到的问题，都已经解决，再次感谢大佬的程序，另外附上我的启动命令行
@echo off
REM 设置项目目录
set SCRIPT_DIR=D:\Game\miniconda3\mc_auto_boss-gpu
set BACKUP_DIR=%SCRIPT_DIR%\background\backup

REM 创建备份目录（如果不存在）
if not exist %BACKUP_DIR% mkdir %BACKUP_DIR%

REM 如果备份文件存在，从备份文件恢复ocr.py
if exist %BACKUP_DIR%\ocr_backup.py copy %BACKUP_DIR%\ocr_backup.py %SCRIPT_DIR%\background\ocr.py

REM 激活conda环境
call conda activate myenv

REM 设置环境变量以避免OpenMP错误
set KMP_DUPLICATE_LIB_OK=TRUE

REM 显示按键说明
echo.
echo -------------------------------
echo 按键说明：
echo F5  - 开始刷BOSS
echo F6  - 开始合成声骸
echo F7  - 暂停运行
echo F12 - 停止运行
echo -------------------------------
echo.

REM 进入项目目录
cd /d %SCRIPT_DIR%

REM 运行Python脚本
python .\background\main.py

REM 显示完成信息
echo.
echo -------------------------------
echo 脚本执行完毕
echo -------------------------------
echo.
pause
